
#TODO Updated list of models and datasets
# DATASETS FOR Quintom MODEL 
#1>PLK18+DESIDR2+PantheonPlus  
#2>PLK18+DESIDR2+Union3
#3>PLK18+DESIDR2+DESY5
[custom]
chainsdir = simplemc/chains/
model = Quintom
prefact = phy
varys8  = False
datasets = PLK18+DESIDR2+DESY5                           
analyzername = mcmc
addDerived = False
mcevidence = True  
mcevidence_k = 2
overwrite = True
getdist = False
corner = False
simpleplot = False
showfig = False
useNeuralLike = False

;----------------------------------------------------------
[mcmc]
;Nsamples
nsamp   = 50000

;Burn-in
skip    = 500

;temperature at which to sample
temp    = 1

;Gelman-Rubin for convergence
GRstop  = 0.01

;every number of steps check the GR-criteria
checkGR = 500

